version: "3"
services:
  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT= 5432
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=kjhdsajkhfuioyhfiuhdiusfjkjhjkkjlkjdskl
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_TIME=30
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: